### ISSUE TITLE
ModuleNotFoundError: No module named 'allow_cidr'

### ISSUE THREAD

**Issue by brandonbryant12** [mozmeao/django-allow-cidr#14]
* Django Allow CIDR version: 0.3.1
* Django version:3.0.8
* Python version: Python 3.7.3
* Operating System: MacOs Catalina 10.15.6

### Description

Following tutorial here https://pypi.org/project/django-allow-cidr/ and getting an error. 

`django-allow-cidr` installed properly 

### What I Did

```
pip3 install django-allow-cidr
```
added to `app.settings.py`
```
MIDDLEWARE = (
    'allow_cidr.middleware.AllowCIDRMiddleware',
)

ALLOWED_CIDR_NETS = ['172.1.1.0/255']
```
run command: `python3 manage.py runserver`

Error:
 `ModuleNotFoundError: No module named 'allow_cidr'`

**Comment by pmac** [comment]
That should work. Are you using a virtualenv that maybe was not being used by either `pip3` or `python3` commands?

**Comment by brandonbryant12** [comment]
thanks for the quick response, 
I am using just my machine, here is the results of `pip3 list`

![Screen Shot 2020-09-11 at 2 12 32 PM](https://user-images.githubusercontent.com/15367258/92958777-d6f5cb80-f438-11ea-9d23-2808c0f7bbc2.png)

**Comment by brandonbryant12** [comment]
actually this fixes it 
`sudo python3 -m pip install django-allow-cidr`
 thanks, still learning python https://docs.python.org/3/installing/index.html

**Comment by pmac** [comment]
No worries. Best of luck with the project.
