### ISSUE TITLE
distutils has been deprecated in Python 3.10

### ISSUE THREAD

**Issue by tirkarthi** [mozmeao/django-allow-cidr#16]
https://www.python.org/dev/peps/pep-0632/#migration-advice

https://github.com/mozmeao/django-allow-cidr/blob/870dd774919c5ba6237fd5fdd71c8e078e6b326b/tests/test_middleware.py#L7

**Comment by pmac** [comment]
Thanks!

**Comment by stevejalim** [comment]
Note: while `StrictVersion` isn't in the tests any more, it is/will soon be in use in the middleware as a roadblock, so it will need updating there before Python 3.12

**Comment by stevejalim** [comment]
Thanks for the poke @n1ngu - I'll get a release out ASAP (might be tomorrow as travelling at the moment)

**Comment by stevejalim** [comment]
https://github.com/mozmeao/django-allow-cidr/pull/23

**Comment by n1ngu** [comment]
No poke intended! Just trying to guide astray people hunting this warning that might be confused by the closed issue.

But thanks for the superfast release, I'll update right away!
