### ISSUE TITLE
Drop netaddr dependency and use ipaddress from standard library?

### ISSUE THREAD

**Issue by n1ngu** [mozmeao/django-allow-cidr#22]
Any roadmap or open debate for dropping the netaddr dependency and use https://docs.python.org/3/library/ipaddress.html ?

Everything works fine but having to install netaddr on python 3.3+ does not feel nice.

APIs aren't identical but hugely equivalent.

**Comment by stevejalim** [comment]
@n1ngu Thanks for the suggestion. Is this something you'd be up for submitting as a PR? I'd be happy to review and test if so. 

If you're short on time/headspace, I'll see if I can get around to it before too long, but it won't be super-soon

**Comment by n1ngu** [comment]
There you go!
