### ISSUE TITLE
Incorrect documentation on Pypi

### ISSUE THREAD

**Issue by whyscream** [mozmeao/django-allow-cidr#8]
* Django Allow CIDR version: 0.3.0
* Django version: 1.11
* Python version: 2.7
* Operating System: -

### Description

The Pypi frontpage for the package documents the settings ALLOW_CIDR_NETS, but the github page uses ALLOWED_CIDR_NETS, and so does the code. Using the first variant obviously doesn't work. 

Please fix the documentation on Pypi (new release?) so the documentation is no longer confusing.

**Comment by pmac** [comment]
Ah! Good catch. I knew we fixed that but forgot that it's still on pypi. I'll get a new release out with hopefully a fix for #6 as well. Thanks!

**Comment by pmac** [comment]
Just released `0.3.1` and with it updated docs. Thanks!
